# Generated by Django 3.0.5 on 2020-06-25 07:12

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200623_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profcessuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that Email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='profcessuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
